package com.rvafin.springjwt.enums;

public enum AdditionalPrompts {
    EXPLAIN_CODE_WITH_COMMENTS(),
    WRITE_CODE_BRIEFLY_POSSIBLE(),
    REMOVE_COMMENTS(),
    RENAME_VARIABLES(),
    REFACTORING_USING_CAMELCASE_METHOD(),
    REFACTORING_USING_SNAKECASE_METHOD()
}
